export const GET_EGRESSES = "GET_EGRESSES";
export const GET_EGRESSES_ERROR = "GET_EGRESSES_ERROR";
export const GET_EGRESSES_SUCCESS = "GET_EGRESSES_SUCCESS";

export const GET_EGRESSES_CATEGORIES = "GET_EGRESSES_CATEGORIES";
export const GET_EGRESSES_CATEGORIES_ERROR = "GET_EGRESSES_CATEGORIES_ERROR";
export const GET_EGRESSES_CATEGORIES_SUCCESS = "GET_EGRESSES_CATEGORIES_SUCCESS";
