export const ADD_NEW_PRODUCT_DETAIL = "ADD_NEW_PRODUCT_DETAIL";

export const REMOVE_ITEM_PRODUCT_DETAIL = "REMOVE_ITEM_SALE_DETAIL";
export const READ_DATA_NEW_SALE = "READ_DATA_NEW_SALE";

export const POST_NEW_SALE = "POST_NEW_SALE";
export const POST_NEW_SALE_SUCCESS = "POST_NEW_SALE_SUCCESS";
export const POST_NEW_SALE_ERROR = "POST_NEW_SALE_ERROR";

