export const ADD_NEW_PRODUCT_DETAIL = "ADD_NEW_PRODUCT_DETAIL";

export const REMOVE_ITEM_PRODUCT_DETAIL = "REMOVE_ITEM_SALE_DETAIL";
export const READ_DATA_NEW_SALE = "READ_DATA_NEW_SALE";
export const READ_DATA_NEW_PRODUCT = "READ_DATA_NEW_PRODUCT";

export const GET_ALL_SALES = "GET_ALL_SALES";
export const GET_ALL_SALES_SUCCESS = "GET_ALL_SALESSUCCESS";
export const GET_ALL_SALES_ERROR = "GET_ALL_SALES_ERROR";

export const POST_NEW_SALE = "POST_NEW_SALE";
export const POST_NEW_SALE_SUCCESS = "POST_NEW_SALE_SUCCESS";
export const POST_NEW_SALE_ERROR = "POST_NEW_SALE_ERROR";

